name: Compilar Add-in Casio

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Actualizar sistema e instalar base
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git cmake ninja python

      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar repositorio Casio en Arch
        run: |
          # Agregar clave y repositorio binario de Lephenixnoir en Arch Linux
          pacman-key --recv-keys 49791EB0417937A5 || pacman-key --recv-keys --keyserver keyserver.ubuntu.com 49791EB0417937A5 || true
          pacman-key --lsign-key 49791EB0417937A5 || true
          cat << 'EOF' >> /etc/pacman.conf
          [casio]
          SigLevel = Never
          Server = https://casio.lephenixnoir.net/archlinux/$arch
          EOF
          pacman -Sy --noconfirm sh-elf-gcc sh-elf-binutils fxsdk gint

      - name: Compilar Add-in
        run: |
          fxsdk build-fx

      - name: Subir binario compilado
        uses: actions/upload-artifact@v4
        with:
          name: casio-addin-fx9860g
          path: |
            build*/*.g1a
            build*/*.g3a
