name: Compilar Add-in Casio

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/lephenixnoir/fxsdk:latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar y compilar proyecto
        run: |
          fxsdk build-fx

      - name: Subir binario compilado
        uses: actions/upload-artifact@v4
        with:
          name: casio-addin-fx9860g
          path: |
            build-fx/*.g1a
            build-fx/*.g3a
